export const SLICE_NAME = "gtfsShst";

export const ITERATE = `${SLICE_NAME}/ITERATE`;

export const NETWORK_REQUESTED = `${SLICE_NAME}/NETWORK_REQUESTED`;
export const NETWORK_RECEIVED = `${SLICE_NAME}/NETWORK_RECEIVED`;
export const GTFS_SHAPES_SELECTED = `${SLICE_NAME}/GTFS_SHAPES_SELECTED`;
export const GTFS_SHAPES_SELECTED_RESET = `${SLICE_NAME}/GTFS_SHAPES_SELECTED_RESET`;

export const NEXT = `${SLICE_NAME}/NEXT`;
export const RETRIEVED_NETEDGE = `${SLICE_NAME}/RETRIEVED_NETEDGE`;
export const MATCHED = `${SLICE_NAME}/MATCHED`;
export const DONE = `${SLICE_NAME}/DONE`;

export const CLOSE = `${SLICE_NAME}/CLOSE`;
export const CLOSED = `${SLICE_NAME}/CLOSED`;
export const RESTART = `${SLICE_NAME}/RESTART`;
