export const SLICE_NAME = "gtfsShst";

export const ITERATE = `${SLICE_NAME}/ITERATE`;

export const GTFS_NETWORK_REQUESTED = `${SLICE_NAME}/GTFS_NETWORK_REQUESTED`;
export const GTFS_NETWORK_RECEIVED = `${SLICE_NAME}/GTFS_NETWORK_RECEIVED`;

export const GTFS_SHAPES_SELECTED = `${SLICE_NAME}/GTFS_SHAPES_SELECTED`;
export const GTFS_SHAPES_SELECTED_RESET = `${SLICE_NAME}/GTFS_SHAPES_SELECTED_RESET`;

export const SHST_MATCHES_REQUESTED = `${SLICE_NAME}/SHST_MATCHES_REQUESTED`;
export const SHST_MATCHES_RECEIVED = `${SLICE_NAME}/SHST_MATCHES_RECEIVED`;
