export const CONNECT = 'REDUX_WEBSOCKET::CONNECT'
export const DISCONNECT = 'REDUX_WEBSOCKET::DISCONNECT'
export const SEND = 'REDUX_WEBSOCKET::SEND'
export const OPEN = 'REDUX_WEBSOCKET::OPEN'
export const CLOSED = 'REDUX_WEBSOCKET::CLOSED'
export const MESSAGE = 'REDUX_WEBSOCKET::MESSAGE'
export const BROKEN = 'REDUX_WEBSOCKET::BROKEN'
export const BEGIN_RECONNECT = 'REDUX_WEBSOCKET::BEGIN_RECONNECT'
export const RECONNECT_ATTEMPT = 'REDUX_WEBSOCKET::RECONNECT_ATTEMPT'
export const RECONNECTED = 'REDUX_WEBSOCKET::RECONNECTED'
export const ERROR = 'REDUX_WEBSOCKET::ERROR'

export default [
  CONNECT,
  DISCONNECT,
  SEND,
  OPEN,
  CLOSED,
  MESSAGE,
  BROKEN,
  BEGIN_RECONNECT,
  RECONNECT_ATTEMPT,
  RECONNECTED,
  ERROR
]
